---
title: "Lab2"
output: html_document
---
### Виконала: *Бокань Вероніка*
### В лабораторній роботі необхідно виконати наступні дії:
### 1. Створить вектор v із 100 елементів командою v <- rnorm(100). Для цього вектору виведіть: 10-й елемент; елементи з 10-го по 20-й включно; 10 елементів починаючи з 20-го; елементи більше 0.  
```{r}
v <- rnorm(100)
v
v[10]
v[10:20]
v[20:(20+10)]
v[v>0]
```

### 2. Створити фрейм (data frame) y командою y <- data.frame(a = rnorm(100), b = 1:100, cc = sample(letters, 100, replace = TRUE)). 
```{r}
y <- data.frame(a = rnorm(100), b = 1:100, cc = sample(letters, 100, replace = TRUE))
y
```

### Для цього data frame виведіть: останні 10 строк; строки з 10 по 20 включно; 10-й елемент стовпця b; повністю стовпець cc, при цьому використайте ім’я стовпця.
```{r}
tail(y,10)

y[10:20,]

y$b[10]

y$cc

```

### 3. Створити вектор z з елементами 1, 2, 3, NA, 4, NA, 5, NA. Для цього вектору: виведіть всі елементи, які не NA; 

```{r}
z <- c(1, 2, 3, NA, 4, NA, 5, NA)
z
bad <- is.na(z)
z[!bad]
```
### Підрахуйте середнє значення всіх елементів цього вектору без NA значень та з NA значеннями.
```{r}
mean(z[!bad])
mean(z)
```

